### ISSUE TITLE
한글자동완성기능 구현 PR에 대한 버그와 의견

### ISSUE THREAD

**Issue by hamsoter** [hamsoter/food-management#13]
<img width="596" alt="스크린샷 2022-08-06 오후 7 01 34" src="https://user-images.githubusercontent.com/100299692/183244223-5f00f3eb-a665-42ef-8fd6-dad44d7dca08.png">
<img width="649" alt="스크린샷 2022-08-06 오후 7 01 03" src="https://user-images.githubusercontent.com/100299692/183244225-6c2819db-4274-4b6a-9cb2-8d0e4bab411c.png">

현재 텍스트 입력시 
노란색으로 칠해지는 '유저가 입력한 텍스트 필드' value에 이상이 있는 거 같습니다! 다가오는 스터디 모임에 이 버그에 대해서 짧게 얘기를 나누면 좋을 것 같습니다 :)

저번 피알을 제가 너무 늦게 본 바람에 이미 반영이 되었지만... ㅠㅠ 얘기를 나눠보고 싶은 부분이 있습니다!

자동완성을 위한 기능이 지금은 `AddMeal` 컴포넌트에 있는데요, 지금은 `AddMeal`페이지에 있는 기능이 이 기능 뿐이라 괜찮을지도 모르지만 차후 `AddMeal` 컴포넌트에 다른 기능도 추가가 될테고, 그러면 `AddMeal` 컴포넌트의 코드는 계속 길어질 거예요 😢 

저희가 처음에 폴더 구조에 대해 고민을 할 당시에 결국 page라는 폴더를 따로 구분해둔 것은 
**이 페이지가 어떤 컴포넌트 조각들로 이루어져 있는지 한번에 알기 쉽게 하기 위해서** 라고 저는 생각했어요 😃 
지금과 같이 진행하다보면 `page컴포넌트가 너무 거대해질 거 같아서 유려됩니다!

가독성을 위해서라도 페이지 컴포넌트(`/pages` 안의 컴포넌트들)는 간략하게 유지하고 지금 만들어두신 음식이름 자동완성 컴포넌트는 component에 한번 쪼갠 후, 이렇게 분리한 컴포넌트를 `AddMeal` 컴포넌트에서 import 해 쓰는 것이 어떨지 제안하고 싶어요. 금곰님의 생각은 어떠신가요? (앗 그리구 첫번째 기능 PR 축하드립니다! 🥳  정말 멋져요!)

**Comment by hamsoter** [comment]
@ShineTiger 확인 부탁드립니다아아아아 🐱

**Comment by ShineTiger** [comment]
오류 확인했습니다! 
자동완성 컴포넌트 쪼개기도 찬성입니다! 지금은 검색창에 붙어있는 형태인데
수정한다면 검색창 하단에 새로운 레이아웃을 만들어서 거기에 자동완성 컴포넌트를 넣을 생각입니다!
