### ISSUE TITLE
[REQUEST] 음식 이름 리스트 가져오는 api 

### ISSUE THREAD

**Issue by ShineTiger** [hamsoter/food-management#18]
### 요청 내용
@Revi-Universe 
음식 이름 리스트를 가져오는 api를 요청드립니다
key값은 영어로 부탁드립니다

### 사용처
검색창 자동완성 리스트에서 사용됩니다
#16  자동완성 컴포넌트 분리

**Comment by Revi-Universe** [comment]
Dotenv 모듈을 이용해서 환경 변수 설정부터 완료한 뒤에 api 만들겠습니다!
