### ISSUE TITLE
음식 이름 검색 자동완성 결과 value 버그

### ISSUE THREAD

**Issue by hamsoter** [hamsoter/food-management#33]
## 이슈 개요

음식 검색시, 색칠되어 나오는 리스트의 value가 이상하게 나오고 있습니다.

ex) '나나' 입력시
바'나나'우유 가 아닌
'나나'바우유
이런 식으로 출력됩니다.

## 요약
- input에 입력된 value 가 무조건 앞에 나오고 있는 것 같습니다. 해당 부분 로직 확인해주세요!

**Comment by ShineTiger** [comment]
https://github.com/hamsoter/food-management/pull/49
버그 해결했습니다!
