### ISSUE TITLE
유저 회원정보 유효성 검사 조건 형식 요청

### ISSUE THREAD

**Issue by Revi-Universe** [hamsoter/food-management#37]
### 요청 내용
로그인, 회원가입 절차에 사용한 각각의 인풋들의 유효성 검사(validation) 조건들을 정리해서 알려주세요!
예) id는 영문 대/소문자 및 숫자만 가능, 5자 이상~17자 이하. 등등등

### 사용처
같은 유효성 조건을 백엔드에서도 검사해야 하는데, 프론트에서 검사하는데 사용한 모듈이나 기능들이 없기때문에 프론트에서 쓴 코드를 그대로 사용할 수가 없습니다. 따라서 제가 백엔드에서 검사하는 코드를 작성해야 하기 때문에 이 조건들이 필요합니다.

**Comment by ShineTiger** [comment]
[ 회원가입 ]
id : 최소 4글자 이상, 15자 이하, 알파벳(대소문자)과 숫자만 가능합니다.
pw: 최소 4글자 이상, 15자 이하, 알파벳(대소문자)과 숫자만 가능합니다.
pw확인 : pw에 적은 값과 일치해야 합니다
닉네임 : 최소 1글자 이상, 15자 이하, 오직 한글로만 가능합니다. 
---
[ 로그인 ]
id,pw : 회원가입과 동일합니다.
---
모든 input에는 required가 적용되어 있습니다!
